import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Loader2, RefreshCw, TrendingUp, Send } from 'lucide-react';

interface CMAEquityRecheckProps {
  reportId: string;
  purchasePrice: number;
  improvementsInvested: number;
  equityRecalcCount: number;
  lastEquityUpdate: string | null;
  fubPersonId: number | null;
  fubPersonName: string | null;
  propertyAddress: string;
  // Current market stats for re-analysis
  medianSalePrice: number | null;
  activeListings: number | null;
  soldListings: number | null;
  avgDaysOnMarket: number | null;
  saleToListRatio: number | null;
  onUpdate: () => void;
}

const CMAEquityRecheck = ({
  reportId,
  purchasePrice,
  improvementsInvested,
  equityRecalcCount,
  lastEquityUpdate,
  fubPersonId,
  fubPersonName,
  propertyAddress,
  medianSalePrice,
  activeListings,
  soldListings,
  avgDaysOnMarket,
  saleToListRatio,
  onUpdate,
}: CMAEquityRecheckProps) => {
  const [recalculating, setRecalculating] = useState(false);
  const [pushingNote, setPushingNote] = useState(false);
  const [result, setResult] = useState<{
    pricingBandLow: number | null;
    pricingBandHigh: number | null;
    pricingBandRecommended: number | null;
    equityLow: number | null;
    equityHigh: number | null;
  } | null>(null);

  const handleRecalculate = async () => {
    setRecalculating(true);
    try {
      // Re-run the cma-analyze edge function
      const { data: fnData, error: fnError } = await supabase.functions.invoke('cma-analyze', {
        body: {
          pdfText: '',
          subjectProperty: { address: propertyAddress },
          purchaseHistory: {
            purchasePrice,
            improvements: improvementsInvested,
          },
          marketStats: {
            method: 'manual',
            medianSalePrice: medianSalePrice?.toString() || null,
            activeListings: activeListings?.toString() || null,
            soldListings: soldListings?.toString() || null,
            avgDOM: avgDaysOnMarket?.toString() || null,
            saleToListRatio: saleToListRatio?.toString() || null,
          },
        },
      });

      if (fnError) throw fnError;

      if (fnData?.success && fnData.analysis) {
        const a = fnData.analysis;
        const eqLow = a.pricing_band_low ? a.pricing_band_low - purchasePrice - improvementsInvested : null;
        const eqHigh = a.pricing_band_high ? a.pricing_band_high - purchasePrice - improvementsInvested : null;
        const now = new Date().toISOString();

        await supabase.from('cma_reports').update({
          pricing_band_low: a.pricing_band_low,
          pricing_band_recommended: a.pricing_band_recommended,
          pricing_band_high: a.pricing_band_high,
          equity_gain_low: eqLow,
          equity_gain_high: eqHigh,
          equity_recalc_count: equityRecalcCount + 1,
          last_equity_update: now,
        } as any).eq('id', reportId);

        setResult({
          pricingBandLow: a.pricing_band_low,
          pricingBandHigh: a.pricing_band_high,
          pricingBandRecommended: a.pricing_band_recommended,
          equityLow: eqLow,
          equityHigh: eqHigh,
        });

        toast.success('Equity recalculated successfully');
        onUpdate();
      } else {
        throw new Error(fnData?.error || 'Analysis failed');
      }
    } catch (err) {
      console.error(err);
      toast.error('Failed to recalculate equity');
    } finally {
      setRecalculating(false);
    }
  };

  const pushUpdatedNote = async () => {
    if (!fubPersonId || !result) return;
    setPushingNote(true);
    try {
      const fmt = (n: number | null) => n != null ? `$${n.toLocaleString()}` : 'N/A';
      const body = [
        `📈 EQUITY UPDATE — ${propertyAddress}`,
        `━━━━━━━━━━━━━━━━━━━━━━━━`,
        `Updated Pricing Band: ${fmt(result.pricingBandLow)} – ${fmt(result.pricingBandHigh)}`,
        `Recommended: ${fmt(result.pricingBandRecommended)}`,
        `Estimated Equity Gain: ${fmt(result.equityLow)} – ${fmt(result.equityHigh)}`,
        `Recalculation #${equityRecalcCount + 1}`,
        `━━━━━━━━━━━━━━━━━━━━━━━━`,
        `Generated by CMA Boss AI`,
      ].join('\n');

      const { data, error } = await supabase.functions.invoke('follow-up-boss', {
        body: {
          action: 'create_note',
          params: {
            personId: fubPersonId,
            subject: `Equity Update: ${propertyAddress}`,
            body,
            isHtml: false,
          },
        },
      });

      if (error) throw error;
      if (!data?.success) throw new Error(data?.error || 'Failed');
      toast.success(`Updated equity note pushed to ${fubPersonName || 'FUB'}`);
    } catch (err) {
      toast.error('Failed to push equity update');
      console.error(err);
    } finally {
      setPushingNote(false);
    }
  };

  const fmt = (n: number | null) => n != null ? `$${n.toLocaleString()}` : '—';

  return (
    <Card className="border-gold/20">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-base flex items-center gap-2">
            <TrendingUp className="h-4 w-4 text-gold" /> Equity Recheck
          </CardTitle>
          <div className="text-xs text-muted-foreground">
            {equityRecalcCount > 0 && <span>Recalculated {equityRecalcCount}x</span>}
            {lastEquityUpdate && (
              <span className="ml-2">
                Last: {new Date(lastEquityUpdate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
              </span>
            )}
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="flex flex-wrap gap-2">
          <Button
            size="sm"
            onClick={handleRecalculate}
            disabled={recalculating}
            className="bg-gold hover:bg-gold/90 text-gold-foreground"
          >
            {recalculating ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <RefreshCw className="h-4 w-4 mr-1" />}
            Recalculate Equity
          </Button>

          {result && fubPersonId && (
            <Button
              size="sm"
              variant="outline"
              onClick={pushUpdatedNote}
              disabled={pushingNote}
              className="border-gold/30 text-gold hover:bg-gold/10"
            >
              {pushingNote ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <Send className="h-4 w-4 mr-1" />}
              Push Updated Note to FUB
            </Button>
          )}
        </div>

        {result && (
          <div className="grid sm:grid-cols-3 gap-3 p-3 rounded-lg bg-muted/30">
            <div>
              <p className="text-xs text-muted-foreground">New Band</p>
              <p className="font-medium text-sm">{fmt(result.pricingBandLow)} – {fmt(result.pricingBandHigh)}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Recommended</p>
              <p className="font-bold text-sm text-gold">{fmt(result.pricingBandRecommended)}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Est. Gain</p>
              <p className={`font-bold text-sm ${(result.equityLow || 0) >= 0 ? 'text-emerald-500' : 'text-destructive'}`}>
                {fmt(result.equityLow)} – {fmt(result.equityHigh)}
              </p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default CMAEquityRecheck;
