import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Loader2, Send, CheckCircle, AlertCircle, RefreshCw } from 'lucide-react';

interface CMAFubPushProps {
  reportId: string;
  fubPersonId: number | null;
  fubPersonName: string | null;
  propertyAddress: string;
  cmaGrade: string | null;
  pricingBandLow: number | null;
  pricingBandRecommended: number | null;
  pricingBandHigh: number | null;
  strategyRecommendation: string | null;
  equityGainLow: number | null;
  equityGainHigh: number | null;
  pricingConfidence: string | null;
  approvedSummary?: string | null;
  approvalStatus?: string;
  onStatusUpdate?: () => void;
}

const CMAFubPush = ({
  reportId,
  fubPersonId,
  fubPersonName,
  propertyAddress,
  cmaGrade,
  pricingBandLow,
  pricingBandRecommended,
  pricingBandHigh,
  strategyRecommendation,
  equityGainLow,
  equityGainHigh,
  pricingConfidence,
  approvedSummary,
  approvalStatus,
  onStatusUpdate,
}: CMAFubPushProps) => {
  const [pushing, setPushing] = useState(false);
  const [pushed, setPushed] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showOverwriteConfirm, setShowOverwriteConfirm] = useState(false);

  const alreadyPushed = approvalStatus === 'pushed';

  if (!fubPersonId) return null;

  const fmt = (n: number | null | undefined) => n != null ? `$${n.toLocaleString()}` : 'N/A';

  const buildNoteBody = () => {
    if (approvedSummary) {
      return [
        `📊 CMA COMPLETED — ${propertyAddress}`,
        `━━━━━━━━━━━━━━━━━━━━━━━━`,
        ``,
        approvedSummary,
        ``,
        `💰 PRICING RANGE`,
        `  Conservative: ${fmt(pricingBandLow)}`,
        `  Recommended:  ${fmt(pricingBandRecommended)}`,
        `  Aggressive:   ${fmt(pricingBandHigh)}`,
        ``,
        `📈 EQUITY SUMMARY`,
        `  Estimated Gain: ${fmt(equityGainLow)} – ${fmt(equityGainHigh)}`,
        ``,
        `━━━━━━━━━━━━━━━━━━━━━━━━`,
        `Generated by CMA Boss AI`,
      ].join('\n');
    }
    return [
      `📊 CMA COMPLETED — ${propertyAddress}`,
      `━━━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      `CMA Grade: ${cmaGrade || 'N/A'} | Confidence: ${pricingConfidence || 'N/A'}`,
      `Strategy: ${strategyRecommendation || 'N/A'}`,
      ``,
      `💰 PRICING RANGE`,
      `  Conservative: ${fmt(pricingBandLow)}`,
      `  Recommended:  ${fmt(pricingBandRecommended)}`,
      `  Aggressive:   ${fmt(pricingBandHigh)}`,
      ``,
      `📈 EQUITY SUMMARY`,
      `  Estimated Gain: ${fmt(equityGainLow)} – ${fmt(equityGainHigh)}`,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Generated by CMA Boss AI`,
    ].join('\n');
  };

  const executePush = async () => {
    setPushing(true);
    setError(null);

    try {
      // 1. Create note
      const noteBody = buildNoteBody();
      const { data: noteData, error: noteErr } = await supabase.functions.invoke('follow-up-boss', {
        body: {
          action: 'create_note',
          params: {
            personId: fubPersonId,
            subject: `CMA Completed – ${propertyAddress}`,
            body: noteBody,
            isHtml: false,
          },
        },
      });
      if (noteErr) throw noteErr;
      if (!noteData?.success) throw new Error(noteData?.error || 'Failed to create note');

      // 2. Add "CMA Sent" tag
      const { error: tagErr } = await supabase.functions.invoke('follow-up-boss', {
        body: {
          action: 'add_tag',
          params: { personId: fubPersonId, tag: 'CMA Sent' },
        },
      });
      if (tagErr) console.warn('Tag add failed:', tagErr.message);

      // 3. Create timeline event
      const { error: eventErr } = await supabase.functions.invoke('follow-up-boss', {
        body: {
          action: 'create_event',
          params: {
            personId: fubPersonId,
            type: 'Other',
            description: `CMA Completed for ${propertyAddress}. Recommended price: ${fmt(pricingBandRecommended)}. Equity range: ${fmt(equityGainLow)} – ${fmt(equityGainHigh)}.`,
          },
        },
      });
      if (eventErr) console.warn('Event create failed:', eventErr.message);

      setPushed(true);
      toast.success(`CMA pushed to ${fubPersonName || 'FUB contact'} with note, tag & timeline event`);

      // Update approval_status to 'pushed'
      if (reportId) {
        await supabase.from('cma_reports').update({
          approval_status: 'pushed',
        } as any).eq('id', reportId);
        onStatusUpdate?.();
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Push failed';
      setError(msg);
      toast.error(`FUB push failed: ${msg}`);
    } finally {
      setPushing(false);
    }
  };

  const handlePush = async () => {
    if (alreadyPushed) {
      setShowOverwriteConfirm(true);
      return;
    }
    await executePush();
  };

  if (pushed) {
    return (
      <div className="flex items-center gap-2 text-emerald-500 text-sm">
        <CheckCircle className="h-4 w-4" />
        <span>Pushed to {fubPersonName || 'FUB'}</span>
      </div>
    );
  }

  return (
    <>
      <div className="flex items-center gap-2">
        <Button
          variant="outline"
          size="sm"
          onClick={handlePush}
          disabled={pushing}
          className="border-gold/30 text-gold hover:bg-gold/10"
        >
          {pushing ? (
            <Loader2 className="h-4 w-4 mr-1 animate-spin" />
          ) : alreadyPushed ? (
            <RefreshCw className="h-4 w-4 mr-1" />
          ) : (
            <Send className="h-4 w-4 mr-1" />
          )}
          {alreadyPushed ? 'Re-push to FUB' : 'Push to FUB'}
        </Button>
        {error && (
          <div className="flex items-center gap-1 text-destructive text-xs">
            <AlertCircle className="h-3 w-3" />
            <span>{error}</span>
          </div>
        )}
      </div>

      <AlertDialog open={showOverwriteConfirm} onOpenChange={setShowOverwriteConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>CMA Already Pushed</AlertDialogTitle>
            <AlertDialogDescription>
              This CMA was already pushed to {fubPersonName || 'the FUB contact'}. 
              Pushing again will create a new note, re-add the tag, and log another timeline event. Continue?
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={() => { setShowOverwriteConfirm(false); executePush(); }}>
              Push Again
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
};

export default CMAFubPush;
