import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Loader2, Send, CheckCircle, AlertCircle } from 'lucide-react';

interface CMAFubPushProps {
  reportId: string;
  fubPersonId: number | null;
  fubPersonName: string | null;
  propertyAddress: string;
  cmaGrade: string | null;
  pricingBandLow: number | null;
  pricingBandRecommended: number | null;
  pricingBandHigh: number | null;
  strategyRecommendation: string | null;
  equityGainLow: number | null;
  equityGainHigh: number | null;
  pricingConfidence: string | null;
  approvedSummary?: string | null;
  approvalStatus?: string;
  onStatusUpdate?: () => void;
}

const CMAFubPush = ({
  reportId,
  fubPersonId,
  fubPersonName,
  propertyAddress,
  cmaGrade,
  pricingBandLow,
  pricingBandRecommended,
  pricingBandHigh,
  strategyRecommendation,
  equityGainLow,
  equityGainHigh,
  pricingConfidence,
  approvedSummary,
  approvalStatus,
  onStatusUpdate,
}: CMAFubPushProps) => {
  const [pushing, setPushing] = useState(false);
  const [pushed, setPushed] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!fubPersonId) return null;

  const fmt = (n: number | null | undefined) => n != null ? `$${n.toLocaleString()}` : 'N/A';

  const handlePush = async () => {
    setPushing(true);
    setError(null);

    try {
      const noteBody = approvedSummary
        ? [
            `📊 CMA REPORT — ${propertyAddress}`,
            `━━━━━━━━━━━━━━━━━━━━━━━━`,
            ``,
            approvedSummary,
            ``,
            `💰 PRICING BAND`,
            `  Conservative: ${fmt(pricingBandLow)}`,
            `  Recommended:  ${fmt(pricingBandRecommended)}`,
            `  Aggressive:   ${fmt(pricingBandHigh)}`,
            ``,
            `📈 ESTIMATED EQUITY GAIN`,
            `  Range: ${fmt(equityGainLow)} – ${fmt(equityGainHigh)}`,
            ``,
            `━━━━━━━━━━━━━━━━━━━━━━━━`,
            `Generated by CMA Boss AI`,
          ].join('\n')
        : [
            `📊 CMA REPORT — ${propertyAddress}`,
            `━━━━━━━━━━━━━━━━━━━━━━━━`,
            ``,
            `CMA Grade: ${cmaGrade || 'N/A'} | Confidence: ${pricingConfidence || 'N/A'}`,
            `Strategy: ${strategyRecommendation || 'N/A'}`,
            ``,
            `💰 PRICING BAND`,
            `  Conservative: ${fmt(pricingBandLow)}`,
            `  Recommended:  ${fmt(pricingBandRecommended)}`,
            `  Aggressive:   ${fmt(pricingBandHigh)}`,
            ``,
            `📈 ESTIMATED EQUITY GAIN`,
            `  Range: ${fmt(equityGainLow)} – ${fmt(equityGainHigh)}`,
            ``,
            `━━━━━━━━━━━━━━━━━━━━━━━━`,
            `Generated by CMA Boss AI`,
          ].join('\n');

      const { data, error: fnError } = await supabase.functions.invoke('follow-up-boss', {
        body: {
          action: 'create_note',
          params: {
            personId: fubPersonId,
            subject: `CMA Report: ${propertyAddress}`,
            body: noteBody,
            isHtml: false,
          },
        },
      });

      if (fnError) throw fnError;

      if (data?.success) {
        setPushed(true);
        toast.success(`CMA note pushed to ${fubPersonName || 'FUB contact'}`);

        // Update approval_status to 'pushed'
        if (reportId) {
          await supabase.from('cma_reports').update({
            approval_status: 'pushed',
          } as any).eq('id', reportId);
          onStatusUpdate?.();
        }
      } else {
        throw new Error(data?.error || 'Failed to create note');
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Push failed';
      setError(msg);
      toast.error(`FUB push failed: ${msg}`);
    } finally {
      setPushing(false);
    }
  };

  if (pushed) {
    return (
      <div className="flex items-center gap-2 text-emerald-500 text-sm">
        <CheckCircle className="h-4 w-4" />
        <span>Pushed to {fubPersonName || 'FUB'}</span>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={handlePush}
        disabled={pushing}
        className="border-gold/30 text-gold hover:bg-gold/10"
      >
        {pushing ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <Send className="h-4 w-4 mr-1" />}
        Push to FUB
      </Button>
      {error && (
        <div className="flex items-center gap-1 text-destructive text-xs">
          <AlertCircle className="h-3 w-3" />
          <span>{error}</span>
        </div>
      )}
    </div>
  );
};

export default CMAFubPush;
