import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { AlertTriangle, Send, Loader2, X } from 'lucide-react';

interface CMAMarketShiftAlertProps {
  reportId: string;
  currentMedian: number | null;
  prevMedian: number | null;
  currentDOM: number | null;
  prevDOM: number | null;
  marketShiftDetected: boolean;
  fubPersonId: number | null;
  fubPersonName: string | null;
  propertyAddress: string;
  onUpdate: () => void;
}

const CMAMarketShiftAlert = ({
  reportId,
  currentMedian,
  prevMedian,
  currentDOM,
  prevDOM,
  marketShiftDetected,
  fubPersonId,
  fubPersonName,
  propertyAddress,
  onUpdate,
}: CMAMarketShiftAlertProps) => {
  const [pushing, setPushing] = useState(false);
  const [dismissed, setDismissed] = useState(false);

  // Calculate shifts
  const medianShift = prevMedian && currentMedian
    ? ((currentMedian - prevMedian) / prevMedian) * 100
    : null;
  const domShift = prevDOM && currentDOM
    ? ((currentDOM - prevDOM) / prevDOM) * 100
    : null;

  const hasMeaningfulShift =
    (medianShift !== null && Math.abs(medianShift) > 5) ||
    (domShift !== null && domShift > 10);

  // Auto-detect and save if not already flagged
  if (hasMeaningfulShift && !marketShiftDetected) {
    supabase.from('cma_reports')
      .update({ market_shift_detected: true } as any)
      .eq('id', reportId)
      .then();
  }

  if (!hasMeaningfulShift || dismissed) return null;

  const pushMarketUpdate = async () => {
    if (!fubPersonId) return;
    setPushing(true);
    try {
      const details = [];
      if (medianShift !== null && Math.abs(medianShift) > 5) {
        details.push(`Median price ${medianShift > 0 ? 'increased' : 'decreased'} by ${Math.abs(medianShift).toFixed(1)}%`);
      }
      if (domShift !== null && domShift > 10) {
        details.push(`Days on market increased by ${domShift.toFixed(1)}%`);
      }

      const body = [
        `⚠️ MARKET SHIFT ALERT — ${propertyAddress}`,
        `━━━━━━━━━━━━━━━━━━━━━━━━`,
        ...details,
        ``,
        `Recommend scheduling a follow-up to discuss updated market conditions.`,
        `━━━━━━━━━━━━━━━━━━━━━━━━`,
        `Generated by CMA Boss AI`,
      ].join('\n');

      const { data, error } = await supabase.functions.invoke('follow-up-boss', {
        body: {
          action: 'create_note',
          params: {
            personId: fubPersonId,
            subject: `Market Shift Alert: ${propertyAddress}`,
            body,
            isHtml: false,
          },
        },
      });

      if (error) throw error;
      if (!data?.success) throw new Error(data?.error || 'Failed');

      toast.success(`Market update pushed to ${fubPersonName || 'FUB'}`);
      setDismissed(true);
    } catch (err) {
      toast.error('Failed to push market update');
      console.error(err);
    } finally {
      setPushing(false);
    }
  };

  return (
    <Alert className="border-amber-500/30 bg-amber-500/5">
      <AlertTriangle className="h-4 w-4 text-amber-500" />
      <AlertTitle className="text-amber-500 font-medium">Market Shift Detected</AlertTitle>
      <AlertDescription className="mt-2">
        <div className="space-y-1 text-sm text-muted-foreground">
          {medianShift !== null && Math.abs(medianShift) > 5 && (
            <p>Median price {medianShift > 0 ? '↑' : '↓'} {Math.abs(medianShift).toFixed(1)}% (${prevMedian?.toLocaleString()} → ${currentMedian?.toLocaleString()})</p>
          )}
          {domShift !== null && domShift > 10 && (
            <p>Days on market ↑ {domShift.toFixed(1)}% ({prevDOM} → {currentDOM} days)</p>
          )}
          <p className="text-amber-500 font-medium mt-2">Recommend client follow-up.</p>
        </div>
        <div className="flex gap-2 mt-3">
          {fubPersonId && (
            <Button
              size="sm"
              variant="outline"
              onClick={pushMarketUpdate}
              disabled={pushing}
              className="border-amber-500/30 text-amber-500 hover:bg-amber-500/10"
            >
              {pushing ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <Send className="h-4 w-4 mr-1" />}
              Push Market Update to FUB
            </Button>
          )}
          <Button size="sm" variant="ghost" onClick={() => setDismissed(true)}>
            <X className="h-4 w-4 mr-1" /> Dismiss
          </Button>
        </div>
      </AlertDescription>
    </Alert>
  );
};

export default CMAMarketShiftAlert;
