// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/get-my-pipeline.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-pipeline.ts
var get_my_pipeline_default = defineTool({
  name: "get_my_pipeline",
  title: "Get my pipeline",
  description: "List the signed-in agent's pipeline clients, with stage, deal category, projected sale amount and projected GCI.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).default(50).describe("Maximum number of pipeline clients to return."),
    status: z.string().trim().optional().describe("Optional status filter, e.g. 'active'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("pipeline_clients").select(
      "id, client_name, client_type, deal_category, stage, status, source, property_address, projected_sale_amount, projected_gci, expected_pending_date, created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ count: data?.length ?? 0, clients: data ?? [] }, null, 2) }],
      structuredContent: { count: data?.length ?? 0, clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-deals.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_my_deals_default = defineTool2({
  name: "get_my_deals",
  title: "Get my deals",
  description: "List the signed-in agent's deals, optionally filtered by stage, including deal value, commission rate and expected close date.",
  inputSchema: {
    stage: z2.string().trim().optional().describe("Optional deal stage filter, e.g. 'lead', 'contacted', 'showing'. Omit for all stages."),
    limit: z2.number().int().min(1).max(200).default(50).describe("Maximum number of deals to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("deals").select(
      "id, client_name, property_address, stage, deal_value, commission_rate, company_split_percentage, source, expected_close_date, created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (stage) query = query.eq("stage", stage);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { count: data?.length ?? 0, stage: stage ?? "all", deals: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-my-weekly-411.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_my_weekly_411_default = defineTool3({
  name: "get_my_weekly_411",
  title: "Get my weekly 4-1-1",
  description: "Return the signed-in agent's recent weekly 4-1-1 accountability entries: goals vs actuals, activity counts and weekly priorities.",
  inputSchema: {
    weeks: z3.number().int().min(1).max(26).default(4).describe("How many recent weeks to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ weeks }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("weekly_411").select(
      "week_start_date, calls_goal, calls_actual, appointments_goal, appointments_actual, listings_goal, listings_actual, contracts_goal, contracts_actual, contacts_made, dials, doors_knocked, appointments_set, appointments_held, contracts_signed, pipeline_additions, firm_deals, priority_1, priority_2, priority_3, priority_4, wins, challenges, next_steps"
    ).eq("user_id", ctx.getUserId()).order("week_start_date", { ascending: false }).limit(weeks ?? 4);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { count: data?.length ?? 0, weeks: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/add-pipeline-client.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var add_pipeline_client_default = defineTool4({
  name: "add_pipeline_client",
  title: "Add pipeline client",
  description: "Add a new client to the signed-in agent's LUXEhub pipeline.",
  inputSchema: {
    client_name: z4.string().trim().min(1).describe("Full name of the client."),
    client_type: z4.string().trim().optional().describe("Buyer, Seller, Tenant, etc."),
    deal_category: z4.string().trim().optional().describe("Deal category, e.g. Sale or Lease."),
    property_address: z4.string().trim().optional(),
    email: z4.string().trim().email().optional(),
    phone: z4.string().trim().optional(),
    source: z4.string().trim().optional().describe("Source of business."),
    projected_sale_amount: z4.number().nonnegative().optional(),
    projected_gci: z4.number().nonnegative().optional(),
    expected_pending_date: z4.string().trim().optional().describe("ISO date (YYYY-MM-DD)."),
    notes: z4.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("pipeline_clients").insert({ ...input, user_id: ctx.getUserId() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added ${input.client_name} to the pipeline.` }],
      structuredContent: { client: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sxpfxmlxegpmfamlmjyg";
var mcp_default = defineMcp({
  name: "luxehub",
  title: "LUXEhub",
  version: "1.0.0",
  instructions: "Tools for LUXEhub, a real estate agent hub. Read the signed-in agent's pipeline clients, deals and weekly 4-1-1 accountability entries, and add new pipeline clients. All data is scoped to the signed-in agent.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_pipeline_default, get_my_deals_default, get_my_weekly_411_default, add_pipeline_client_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
